import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {hash} from '../mock-server/domain.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const exchanges=[];let base,child;const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'semovix-ontology-'));
const API='/api/v1/ontology', M=API+'/models/drkn-core',CS=M+'/changesets/cs-drkn-demo';
let seq=0;
async function start() {
 child=spawn(process.execPath,[path.join(ROOT,'mock-server/server.mjs')],{env:{...process.env,PORT:'0',ENABLE_DEMO_RESET:'true',MOCK_JOB_DELAY_MS:'25',MOCK_DB_PATH:path.join(tmp,'db.json')},stdio:['ignore','pipe','pipe']});
 let logs='';
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error(logs||'server timeout')),10000);child.stdout.on('data',x=>{logs+=x;const m=logs.match(/SEMOVIX_MOCK_READY (http:\/\/127.0.0.1:\d+)/);if(m){base=m[1];clearTimeout(timer);resolve();}});child.stderr.on('data',x=>{logs+=x;});child.on('exit',c=>{clearTimeout(timer);if(!base)reject(Error(logs+'exit '+c));});});
}
async function stop(){if(!child||child.exitCode!==null)return;await new Promise(resolve=>{child.once('exit',resolve);child.kill('SIGTERM');});}
async function api(method,url,body,opts={}) {
 const headers={'Authorization':'Bearer '+(opts.token||'demo-maintainer'),'X-Workspace-Id':opts.workspace||'ws-demo',...(method==='GET'?{}:{'Content-Type':'application/json'}),...(method==='GET'?{}:{'Idempotency-Key':opts.key||`test-${++seq}`}),...opts.headers};
 if(opts.etag!==undefined)headers['If-Match']=opts.etag;
 const response=await fetch(base+url,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}), data=await response.json();
 exchanges.push({method,url,status:response.status,request:body??null,response:data});
 return {status:response.status,data:data.data,error:data.error,headers:response.headers};
}
async function reset(){const r=await api('POST','/__demo/reset',{confirmation:'RESET_DEMO_DATA'});assert.equal(r.status,200);}
async function job(endpoint,revision=12,et=`"cs-drkn-demo:r${revision}"`){const r=await api('POST',CS+'/'+endpoint,{revision},{etag:et});assert.equal(r.status,202,JSON.stringify(r));for(let i=0;i<60;i++){const j=await api('GET',M+'/jobs/'+r.data.id);if(j.data.status!=='RUNNING')return j.data;await new Promise(x=>setTimeout(x,15));}throw Error('job timeout');}
async function fix(){const r=await api('POST',CS+'/operations',{operations:[{op:'UPSERT',collection:'dependencies',id:'runtime',value:{id:'runtime',packageId:'runtime',versionId:'v1.0.0'}}]},{etag:'"cs-drkn-demo:r12"'});assert.equal(r.status,200,JSON.stringify(r));assert.equal(r.data.revision,13);return r.data;}
async function publish(rev=13,opts={}){const v=await job('validation-runs',rev),i=await job('impact-analyses',rev);return api('POST',CS+'/publications',{revision:rev,validationRunId:v.id,impactAnalysisId:i.id,releaseNotes:'演示发布',acknowledgePartialCoverage:true},{etag:`"cs-drkn-demo:r${rev}"`,...opts});}
await test('Semovix ontology HTTP reference implementation',async t=>{
 await start();
 try{
 await t.test('健康接口与读取模型是真实 HTTP',async()=>{assert.equal((await api('GET','/health')).status,200);const r=await api('GET',API+'/models');assert.equal(r.data.total,2);assert.equal((await api('GET',API+'/session')).data.mode,'DEMO');});
 await t.test('全部页面读取同一快照，图表关系一致',async()=>{const v=(await api('GET',M+'/view?changeSetId=cs-drkn-demo&revision=12')).data;for(const k of ['object-types','relations','constraints','actions','implementation-bindings','workflow-refs']){const r=await api('GET',M+'/'+k+'?changeSetId=cs-drkn-demo&revision=12&limit=200');assert.equal(r.status,200);}const g=(await api('GET',M+'/graph?changeSetId=cs-drkn-demo&revision=12')).data;assert.equal(g.contentHash,v.contentHash);assert.deepEqual(g.edges,v.document.relations);assert.equal(g.nodes.length,31);});
 await t.test('模型和工作空间隔离，不以 DRKN 标签冒充模型 ID',async()=>{const a=await api('GET',API+'/models/public-service/view?versionId=v1.0.0');assert.equal(a.data.document.objectTypes.length,1);const b=await api('GET',M,undefined,{workspace:'ws-isolation'});assert.match(b.data.name,/隔离/);assert.equal((await api('GET',M,undefined,{workspace:'ws-ungranted'})).status,403);assert.equal((await api('GET',API+'/models/missing')).status,404);});
 await t.test('精确视图引用必填，不接受同时版本和草稿',async()=>{for(const suffix of ['/view','/view?versionId=v1.3.0&changeSetId=cs-drkn-demo','/view?changeSetId=cs-drkn-demo','/view?changeSetId=cs-drkn-demo&revision=NaN'])assert.equal((await api('GET',M+suffix)).status,400);});
 await t.test('只读身份可查看不能写入，未认证返回401',async()=>{assert.equal((await api('GET',M,undefined,{token:'invalid'})).status,401);const v=await api('GET',M+'/view?changeSetId=cs-drkn-demo&revision=12',undefined,{token:'demo-viewer'});assert.equal(v.data.readOnly,true);assert.equal((await api('POST',CS+'/validation-runs',{revision:12},{token:'demo-viewer',etag:'"cs-drkn-demo:r12"'})).status,403);});
 await t.test('缺少If-Match返回428，错误修订返回412',async()=>{assert.equal((await api('POST',CS+'/validation-runs',{revision:12})).status,428);assert.equal((await api('POST',CS+'/validation-runs',{revision:12},{etag:'"cs-drkn-demo:r2"'})).status,412);});
 await t.test('r12由实际缺失依赖产生阻断而非写死失败',async()=>{const v=await job('validation-runs');assert.equal(v.status,'SUCCEEDED');assert.equal(v.result.passed,false);assert(v.result.issues.some(i=>i.code==='DEPENDENCY_VERSION_REQUIRED'));assert.equal(v.isCurrent,true);});
 await t.test('阻断未修复不能发布',async()=>{const r=await publish(12);assert.equal(r.status,409);assert.equal(r.error.code,'VALIDATION_BLOCKED');});
 await t.test('请求Schema拒绝额外字段和缺字段',async()=>{assert.equal((await api('POST',CS+'/operations',{operations:[],fake:1},{etag:'"cs-drkn-demo:r12"'})).status,422);assert.equal((await api('POST',CS+'/operations',{operations:[{op:'UPSERT',collection:'dependencies',id:'runtime',value:{id:'runtime'}}]},{etag:'"cs-drkn-demo:r12"'})).status,422);});
 await t.test('批量操作全成或全败，不留下部分修改',async()=>{const r=await api('POST',CS+'/operations',{operations:[{op:'UPSERT',collection:'dependencies',id:'runtime',value:{id:'runtime',packageId:'runtime',versionId:'v1.0.0'}},{op:'REMOVE',collection:'objectTypes',id:'does-not-exist'}]},{etag:'"cs-drkn-demo:r12"'});assert.equal(r.status,404);assert.equal((await api('GET',CS)).data.revision,12);});
 await t.test('修复变为r13，正式版本与r12历史均不变',async()=>{const old=(await api('GET',M+'/versions/v1.3.0')).data;await fix();const curr=(await api('GET',M+'/versions/v1.3.0')).data;assert.deepEqual(curr,old);const hist=(await api('GET',M+'/view?changeSetId=cs-drkn-demo&revision=12')).data;assert.equal(hist.readOnly,true);assert.equal(hist.document.dependencies.find(x=>x.id==='runtime').versionId,null);const v=await job('validation-runs',13);assert.equal(v.result.passed,true,JSON.stringify(v.result));});
 await t.test('保存后旧ETag不能覆盖新修订',async()=>{assert.equal((await api('POST',CS+'/operations',{operations:[{op:'REMOVE',collection:'objectTypes',id:'Field'}]},{etag:'"cs-drkn-demo:r12"'})).status,412);});
 await t.test('Diff来自真实草稿，含dependency变化',async()=>{const r=await api('GET',CS+'/diff?revision=13');assert.equal(r.status,200);assert(r.data.items.some(x=>x.collection==='objectTypes'&&x.id==='SemanticAssertion'));});
 await t.test('校验结果绑定修订，保存后旧报告失效',async()=>{const v=await job('validation-runs',13),i=await job('impact-analyses',13);const typ=(await api('GET',M+'/view?changeSetId=cs-drkn-demo&revision=13')).data.document.objectTypes.find(t=>t.id==='Field');typ.definition+=' 仅说明变化。';assert.equal((await api('POST',CS+'/operations',{operations:[{op:'UPSERT',collection:'objectTypes',id:'Field',value:typ}]},{etag:'"cs-drkn-demo:r13"'})).status,200);assert.equal((await api('GET',M+'/jobs/'+v.id)).data.isCurrent,false);const r=await api('POST',CS+'/publications',{revision:14,validationRunId:v.id,impactAnalysisId:i.id,releaseNotes:'过期报告',acknowledgePartialCoverage:true},{etag:'"cs-drkn-demo:r14"'});assert.equal(r.error.code,'REPORT_STALE');});
 await t.test('依赖影响由引用路径产生并披露未知范围',async()=>{const i=await job('impact-analyses',14);assert.equal(i.result.inventoryCompleteness,'PARTIAL');assert(i.result.items.some(x=>x.kind==='CONSUMER'));assert.equal(i.result.consumerPinUpdates,0);});
 await t.test('发布必须知悉不完整影响范围，不能默认假装完整',async()=>{const v=await job('validation-runs',14),i=await job('impact-analyses',14);const r=await api('POST',CS+'/publications',{revision:14,validationRunId:v.id,impactAnalysisId:i.id,releaseNotes:'测试',acknowledgePartialCoverage:false},{etag:'"cs-drkn-demo:r14"'});assert.equal(r.error.code,'IMPACT_ACK_REQUIRED');});
 await t.test('成功发布与幂等重试只产生同一个版本',async()=>{const v=await job('validation-runs',14),i=await job('impact-analyses',14),body={revision:14,validationRunId:v.id,impactAnalysisId:i.id,releaseNotes:'成功演示',acknowledgePartialCoverage:true},opts={etag:'"cs-drkn-demo:r14"',key:'publish-same-key'};const first=await api('POST',CS+'/publications',body,opts);assert.equal(first.status,201,JSON.stringify(first));const second=await api('POST',CS+'/publications',body,opts);assert.equal(second.status,201);assert.equal(first.data.id,second.data.id);assert.equal(second.headers.get('idempotent-replayed'),'true');assert.equal((await api('POST',CS+'/publications',{...body,releaseNotes:'不同参数'},opts)).status,409);assert.equal((await api('GET',M)).data.currentVersionId,'v1.4.0');assert.equal((await api('GET',CS)).data.status,'PUBLISHED');assert.equal(first.data.workflowStarted,false);assert.equal(first.data.consumerPinsUpdated,false);const registry=(await api('GET',API+'/registry')).data;assert(registry.consumers.every(x=>x.pinnedVersionId==='v1.3.0'));});
 await t.test('发布后不能原地修改；版本和审计可查询',async()=>{assert.equal((await api('POST',CS+'/operations',{operations:[{op:'REMOVE',collection:'objectTypes',id:'Field'}]},{etag:'"cs-drkn-demo:r14"'})).status,409);assert.equal((await api('GET',M+'/versions')).data.total,2);assert((await api('GET',M+'/audit-events?limit=200')).data.items.some(x=>x.eventType==='ONTOLOGY_VERSION_PUBLISHED'));});
 await t.test('重启保留发布与草稿，不依赖浏览器本地缓存',async()=>{await stop();base=null;await start();assert.equal((await api('GET',M)).data.currentVersionId,'v1.4.0');assert.equal((await api('GET',CS)).data.status,'PUBLISHED');});
 await t.test('新草稿必须当前基线，可显式恢复历史快照但不覆盖历史',async()=>{assert.equal((await api('POST',M+'/changesets',{name:'旧基线',reason:'测试',baseVersionId:'v1.3.0',targetVersionId:'v1.5.0'})).status,409);const r=await api('POST',M+'/changesets',{name:'回到历史结构的修订',reason:'显示回退影响',baseVersionId:'v1.4.0',restoreFromVersionId:'v1.3.0',targetVersionId:'v1.5.0'});assert.equal(r.status,201);const d=(await api('GET',M+'/view?changeSetId='+r.data.id+'&revision=0')).data;assert.equal(d.contentHash,(await api('GET',M+'/versions/v1.3.0')).data.contentHash);const a=await api('POST',M+'/changesets/'+r.data.id+'/abandon',{reason:'演示结束'},{etag:r.data.etag});assert.equal(a.data.status,'ABANDONED');assert.equal((await api('GET',M)).data.currentVersionId,'v1.4.0');});
 await t.test('新建业务模型产生真实记录与草稿，不只是路由跳转',async()=>{const r=await api('POST',API+'/models',{id:'new-business',name:'演示业务本体',profile:'BUSINESS',ownerRef:'demo-team'});assert.equal(r.status,201);assert.equal(r.data.model.currentVersionId,null);assert.equal((await api('GET',API+'/models/new-business/changesets')).data.total,1);assert.equal((await api('GET',API+'/models/new-business',undefined,{workspace:'ws-isolation'})).status,404);});
 await t.test('行动用例：低分有依据通过，高分仅LLM拒绝，均不修改本体',async()=>{const before=(await api('GET',M)).data.currentVersionHash;for(const [f,expected] of [['assertion-good','ALLOW'],['assertion-llm-only','DENY'],['assertion-stale','DENY']]){const r=await api('POST',M+'/action-tests',{view:{versionId:'v1.4.0'},actionId:'confirmAssertion',fixtureId:f});assert.equal(r.data.decision,expected);assert.equal(r.data.realExecution,false);assert.equal(r.data.modelChanged,false);}assert.equal((await api('GET',M)).data.currentVersionHash,before);});
 await t.test('行动用例：创建连接不扫描，不支持扫描的连接器明确拒绝',async()=>{const good=await api('POST',M+'/action-tests',{view:{versionId:'v1.4.0'},actionId:'createDataSource',fixtureId:'source-verified'});assert.equal(good.data.simulatedAfterState.scanStarted,false);const bad=await api('POST',M+'/action-tests',{view:{versionId:'v1.4.0'},actionId:'startMetadataScan',fixtureId:'scan-unsupported'});assert.equal(bad.data.decision,'DENY');assert((await api('GET',API+'/action-fixtures')).data.total>0);});
 await t.test('无效关系目标、基数、实现契约不能通过校验',async()=>{await reset();await fix();const view=(await api('GET',M+'/view?changeSetId=cs-drkn-demo&revision=13')).data;const r=view.document.relations.find(x=>x.id==='has_assertion');r.targetTypeId='MissingType';r.targetCardinality={min:2,max:1};const b=view.document.implementationBindings[0];b.inputContractRef='wrong@1';const save=await api('POST',CS+'/operations',{operations:[{op:'UPSERT',collection:'relations',id:r.id,value:r},{op:'UPSERT',collection:'implementationBindings',id:b.id,value:b}]},{etag:'"cs-drkn-demo:r13"'});assert.equal(save.status,200);const v=await job('validation-runs',14);assert(!v.result.passed);for(const code of ['RELATION_TARGET_NOT_FOUND','CARDINALITY_INVALID','IMPLEMENTATION_CONTRACT_MISMATCH'])assert(v.result.issues.some(x=>x.code===code));});
 await t.test('新建系统内核不允许借业务创建接口绕过',async()=>{assert.equal((await api('POST',API+'/models',{id:'rogue-core',name:'假系统模型',profile:'DATA_GOVERNANCE',ownerRef:'x'})).status,422);});
 await t.test('重置只影响当前演示工作空间',async()=>{await reset();assert.equal((await api('GET',M)).data.currentVersionId,'v1.3.0');assert.equal((await api('GET',CS)).data.revision,12);assert.equal((await api('GET',M,undefined,{workspace:'ws-isolation'})).data.currentVersionId,'v1.3.0');});
 } finally {
 await stop();fs.writeFileSync(path.join(ROOT,'tests/http-exchanges.json'),JSON.stringify(exchanges,null,2));fs.rmSync(tmp,{recursive:true,force:true});
 }
});
